### ISSUE TITLE
WebView dependency issue in IOS 18/XCode 16

### ISSUE THREAD

**Issue by mosabalrsaheed** [devkrest/flutter_story_presenter#16]
Cannot build with the new XCode/IOS update.

Expected result:
Application builds successfully 

Actual result:

Launching lib/main.dart on iPhone 16 Pro Max in debug mode...
Xcode build done.                                           28.7s
Failed to build iOS app
Swift Compiler Error (Xcode): Method does not override any method from its superclass
/Users/z3r0/.pub-cache/hosted/pub.dev/flutter_inappwebview_ios-1.0.13/ios/Classes/InAppWebView/InAppWebView.swift:1431:25

Swift Compiler Error (Xcode): Ambiguous use of 'evaluateJavaScript(_:completionHandler:)'
/Users/z3r0/.pub-cache/hosted/pub.dev/flutter_inappwebview_ios-1.0.13/ios/Classes/InAppWebView/InAppWebView.swift:1035:20

**Comment by Kaival-Patel** [comment]
Hello @mosabalrsaheed. Thanks for issuing the bug. Our team will soon fix this, please note as this is occurring in the latest Xcode version and iOS, it could take time for us to review and address this. We also need to update our macs inorder to have a check.

**Comment by harshlet** [comment]
@mosabalrsaheed 

Here's the answer formatted for posting on GitHub:

---

### Issue Resolution Steps

This issue is not related to the plugin. Follow these steps to resolve it in your project:

1. **Delete `Podfile.lock`:**  
   Navigate to the `ios` folder of your project and delete the `Podfile.lock` file.

2. **Clean the Flutter Project:**  
   Run the following command in your terminal:  
   ```bash
   flutter clean
   ```

3. **Fetch Dependencies:**  
   Execute this command to fetch all dependencies:  
   ```bash
   flutter pub get
   ```

4. **Update CocoaPods:**  
   Navigate to the `ios` folder and run:  
   ```bash
   pod install --repo-update
   ```

5. **Run Your Project:**  
   Build and run your project to ensure the issue is resolved.

If the problem persists, verify that your Flutter and CocoaPods versions are up-to-date.
